[package]
name = "dabengine"
version = "0.1.0"
authors = ["Andrew Medworth <github@medworth.org.uk>"]
edition = "2021"

[dependencies]
rand = "0.8"
regex = "1"
time = "0.2"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "benchmarks"
harness = false
